import { Article } from '../types';

export const STATIC_NEWS: Article[] = [
    {
        id: "static-1",
        source: "FutureTech Now",
        headline: "Project Chimera: The Dawn of Neural-Fabric Computing",
        summary: "A new architecture that mimics the human brain's neural pathways, promising processing speeds previously thought impossible.",
        fullArticle: "In a landmark announcement, startup 'Ethereal Machines' has unveiled 'Project Chimera,' a revolutionary computing architecture. Unlike traditional silicon-based processors, Chimera utilizes a synthetic neural fabric that allows for parallel processing on an unprecedented scale, potentially accelerating AI training and complex simulations by orders of magnitude.",
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        category: "AI",
    },
    {
        id: "static-2",
        source: "The Quantum Daily",
        headline: "Stable Qubits Achieved at Room Temperature, a Major Leap for Quantum Computing",
        summary: "Researchers have successfully maintained a stable quantum state for over a minute without cryogenic cooling.",
        fullArticle: "A breakthrough paper published in 'Nature Physics' details a new method for stabilizing qubits using electromagnetic fields at ambient temperatures. This discovery removes one of the biggest and most expensive hurdles for practical quantum computing, paving the way for smaller, more accessible quantum machines.",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        category: "Gadgets",
    },
    {
        id: "static-3",
        source: "BioInnovate",
        headline: "CRISPR-GeneOS Delivers First Successful In-Vivo Cellular Repair",
        summary: "A new delivery system for CRISPR technology has successfully repaired damaged cells directly within a living organism.",
        fullArticle: "Scientists at the BioSynth Institute have developed 'GeneOS,' a viral vector delivery system that can target specific cells in the body and perform precise genetic edits. The first successful trials in lab mice have shown remarkable results in reversing genetic disorders, opening a new frontier in personalized medicine.",
        timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        category: "Other",
    },
    {
        id: "static-os-1",
        source: "Kernel Corner",
        headline: "Helios OS Achieves POSIX Compliance, Eyes Mainstream Adoption",
        summary: "The independently developed Helios microkernel operating system has now achieved full POSIX compliance, a major milestone for compatibility.",
        fullArticle: "The Helios OS project, known for its focus on security and modularity, announced today that its latest version is now fully POSIX compliant. This allows a vast library of existing Unix and Linux software to be compiled and run on Helios with little to no modification, opening the door for the OS to move from a niche hobbyist project to a potential choice for servers and embedded systems.",
        timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        category: "OS",
    },
    {
        id: "static-4",
        source: "AR/VR Weekly",
        headline: "LightField Displays Are Here: 'Mimesis' Glasses Offer True Holographic Vision",
        summary: "A new player in the AR space has debuted glasses that project true 3D light fields, eliminating screen-door effect and eye strain.",
        fullArticle: "'Mimesis Optics' has come out of stealth with a pair of augmented reality glasses that don't use traditional waveguides or screens. Instead, they project a light field directly onto the user's retina, creating objects that are indistinguishable from reality and can be focused on naturally, just like real-world objects.",
        timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        category: "Gadgets",
    },
     {
        id: "static-5",
        source: "Energy X",
        headline: "Solid-State Hydrogen Fuel Cell Hits 90% Efficiency",
        summary: "A breakthrough in material science has led to a new type of hydrogen fuel cell that is safer, cheaper, and more efficient.",
        fullArticle: "A research consortium has developed a new solid-state electrolyte that dramatically improves the efficiency and safety of hydrogen fuel cells. This innovation could be the key to unlocking hydrogen as a viable, mainstream clean energy source for transportation and grid storage, as it eliminates the need for high-pressure, flammable hydrogen gas storage.",
        timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
        category: "Other",
    },
    {
        id: "static-6",
        source: "Space Explorer",
        headline: "AI Discovers Potentially Habitable Exoplanet System in Old Kepler Data",
        summary: "A specialized AI trained on planetary transit data has identified a previously missed system of three 'super-Earths' in the habitable zone.",
        fullArticle: "By applying a new deep learning model to archived data from the Kepler Space Telescope, astronomers have uncovered the Kepler-186f system's previously unknown siblings. The AI model was able to detect faint transit signals that were previously dismissed as noise, revealing a system with three rocky planets that could potentially harbor liquid water.",
        timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        category: "AI",
    },
     {
        id: "static-7",
        source: "Robotics Today",
        headline: "Swarm Robotics Construct First Autonomous Habitat on Test Site",
        summary: "A fleet of 50 autonomous robots has successfully 3D-printed and assembled a habitable structure with zero human intervention.",
        fullArticle: "The 'Archinaut' project demonstrated a significant milestone in construction robotics. A swarm of specialized robots, coordinated by a central AI, autonomously excavated materials, 3D-printed structural components, and assembled a 400-square-foot dome in under 72 hours. This technology has major implications for disaster relief and off-world construction.",
        timestamp: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
        category: "AI",
    },
    {
        id: "static-8",
        source: "Digital Trends",
        headline: "The 'Ethical AI' Bill Passes Unanimously, Mandating Transparency Audits",
        summary: "A new piece of legislation requires all companies deploying high-impact AI models to undergo regular third-party audits for bias and transparency.",
        fullArticle: "In a rare show of bipartisan unity, lawmakers passed the 'AI Accountability Act'. The law mandates that AI systems used in critical sectors like finance, hiring, and law enforcement must be auditable and their decision-making processes explainable. Companies found non-compliant face significant fines, marking a new era of AI regulation.",
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        category: "AI",
    }
];